import React from "react";
import Header from "../components/Header.jsx";
import Footer from "../components/Footer.jsx";
import I18nText from "../components/I18nText.jsx";
import { useNavScroll } from "../hooks/useNavScroll.js";
import "../styles/home.css";
import "../styles/privacy.css";

const RELEASES = [
  {
    version: "1.0.6",
    date: "2026-06-05",
    title: {
      en: "Pinned sync, Snippet hotkeys, and smarter privacy exclusions",
      zh: "置顶同步、Snippet 快捷键与更智能的隐私排除",
      ja: "ピン留め同期、Snippet ホットキー、より賢いプライバシー除外",
      ko: "고정 동기화, Snippet 단축키 및 더 스마트한 개인정보 제외",
      fr: "Synchronisation des elements epingles, raccourcis Snippet et exclusions plus intelligentes",
      de: "Synchronisierung angehefteter Inhalte, Snippet-Tastenkurzel und intelligentere Datenschutzausschluesse",
      it: "Sincronizzazione degli elementi fissati, scorciatoie Snippet ed esclusioni privacy piu intelligenti",
      es: "Sincronizacion de elementos fijados, atajos de Snippet y exclusiones de privacidad mas inteligentes",
    },
    notes: [
      {
        en: "Added pinned content sync, which can be enabled in Settings and pointed to iCloud Drive or another sync folder. Only pinned clipboard records are synced.",
        zh: "新增置顶内容同步功能，可在设置中开启并选择 iCloud Drive 或其他同步文件夹，仅同步已置顶的剪贴板记录。",
        ja: "設定で有効化し、iCloud Drive または別の同期フォルダを選択できるピン留めコンテンツ同期を追加しました。同期されるのはピン留めされたクリップボード記録のみです。",
        ko: "설정에서 켜고 iCloud Drive 또는 다른 동기화 폴더를 선택할 수 있는 고정 콘텐츠 동기화를 추가했습니다. 고정된 클립보드 기록만 동기화됩니다.",
        fr: "Ajout de la synchronisation du contenu epingle, activable dans les reglages avec iCloud Drive ou un autre dossier de synchronisation. Seuls les enregistrements epingles du presse-papiers sont synchronises.",
        de: "Synchronisierung angehefteter Inhalte hinzugefuegt. Sie kann in den Einstellungen aktiviert und auf iCloud Drive oder einen anderen Sync-Ordner gelegt werden. Synchronisiert werden nur angeheftete Zwischenablageeintraege.",
        it: "Aggiunta la sincronizzazione dei contenuti fissati, attivabile nelle impostazioni scegliendo iCloud Drive o un'altra cartella di sincronizzazione. Vengono sincronizzati solo i record degli appunti fissati.",
        es: "Se agrego sincronizacion de contenido fijado, que puede activarse en Ajustes y apuntar a iCloud Drive u otra carpeta sincronizada. Solo se sincronizan los registros fijados del portapapeles.",
      },
      {
        en: "Pinned sync stores data in a separate `CliboPinnedClips.json` file, while local clipboard history remains in the local database.",
        zh: "置顶同步使用独立 `CliboPinnedClips.json` 文件保存数据，本地剪贴板历史仍保存在本机数据库中。",
        ja: "ピン留め同期のデータは独立した `CliboPinnedClips.json` ファイルに保存され、ローカルのクリップボード履歴は引き続き本体のデータベースに保存されます。",
        ko: "고정 동기화 데이터는 별도의 `CliboPinnedClips.json` 파일에 저장되며, 로컬 클립보드 기록은 계속 로컬 데이터베이스에 저장됩니다.",
        fr: "La synchronisation des elements epingles enregistre les donnees dans un fichier `CliboPinnedClips.json` separe, tandis que l'historique local du presse-papiers reste dans la base locale.",
        de: "Die Synchronisierung angehefteter Inhalte speichert Daten in einer separaten Datei `CliboPinnedClips.json`; der lokale Zwischenablageverlauf bleibt in der lokalen Datenbank.",
        it: "La sincronizzazione degli elementi fissati salva i dati in un file separato `CliboPinnedClips.json`, mentre la cronologia locale degli appunti resta nel database locale.",
        es: "La sincronizacion de elementos fijados guarda los datos en un archivo independiente `CliboPinnedClips.json`, mientras el historial local del portapapeles permanece en la base de datos local.",
      },
      {
        en: "Pinned sync now includes cross-device merge logic for pinned, unpinned, and deleted states, preventing deleted pinned content from being restored by another Mac.",
        zh: "置顶同步新增跨设备合并逻辑，支持同步置顶、取消置顶和删除状态，避免已删除的置顶内容被其他 Mac 重新恢复。",
        ja: "ピン留め同期にクロスデバイスのマージロジックを追加し、ピン留め、ピン留め解除、削除状態を同期できるようにしました。削除済みのピン留め内容が別の Mac から復元されることを防ぎます。",
        ko: "고정 동기화에 기기 간 병합 로직을 추가해 고정, 고정 해제, 삭제 상태를 동기화합니다. 삭제된 고정 콘텐츠가 다른 Mac에서 다시 복원되는 일을 방지합니다.",
        fr: "La synchronisation des elements epingles inclut une logique de fusion entre appareils pour les etats epingle, desepingle et supprime, afin d'eviter qu'un element epingle supprime soit restaure par un autre Mac.",
        de: "Die Synchronisierung angehefteter Inhalte enthaelt jetzt eine geraeteuebergreifende Zusammenfuehrung fuer angeheftete, geloeste und geloeschte Zustaende, damit geloeschte angeheftete Inhalte nicht von einem anderen Mac wiederhergestellt werden.",
        it: "La sincronizzazione degli elementi fissati include una logica di unione tra dispositivi per stati fissati, non fissati ed eliminati, evitando che un contenuto fissato eliminato venga ripristinato da un altro Mac.",
        es: "La sincronizacion de elementos fijados ahora incluye fusion entre dispositivos para estados fijados, desfijados y eliminados, evitando que otro Mac restaure contenido fijado que ya se elimino.",
      },
      {
        en: "Added global Snippet hotkeys for binding common snippets to `Command + Shift + 1` through `Command + Shift + 9` and pasting them quickly in any app.",
        zh: "新增 Snippet 全局快捷键，可将常用片段绑定到 `Command + Shift + 1` 至 `Command + Shift + 9`，在任意应用中快速粘贴。",
        ja: "Snippet のグローバルホットキーを追加し、よく使うスニペットを `Command + Shift + 1` から `Command + Shift + 9` に割り当て、任意のアプリで素早く貼り付けられるようにしました。",
        ko: "Snippet 전역 단축키를 추가해 자주 쓰는 조각을 `Command + Shift + 1`부터 `Command + Shift + 9`까지 연결하고 모든 앱에서 빠르게 붙여넣을 수 있습니다.",
        fr: "Ajout de raccourcis globaux Snippet pour associer les fragments courants a `Command + Shift + 1` jusqu'a `Command + Shift + 9` et les coller rapidement dans n'importe quelle app.",
        de: "Globale Snippet-Tastenkurzel hinzugefuegt, um haeufig genutzte Snippets mit `Command + Shift + 1` bis `Command + Shift + 9` zu verknuepfen und in jeder App schnell einzufuegen.",
        it: "Aggiunte scorciatoie globali Snippet per collegare i frammenti comuni a `Command + Shift + 1` fino a `Command + Shift + 9` e incollarli rapidamente in qualsiasi app.",
        es: "Se agregaron atajos globales de Snippet para vincular fragmentos comunes a `Command + Shift + 1` hasta `Command + Shift + 9` y pegarlos rapidamente en cualquier app.",
      },
      {
        en: "Snippet hotkeys can be assigned or cleared from Settings, the Dashboard context menu, and the quick panel context menu.",
        zh: "Snippet 快捷键可在设置、Dashboard 右键菜单和快捷面板右键菜单中分配或清除。",
        ja: "Snippet ホットキーは、設定、Dashboard のコンテキストメニュー、クイックパネルのコンテキストメニューから割り当てまたは解除できます。",
        ko: "Snippet 단축키는 설정, Dashboard 컨텍스트 메뉴, 빠른 패널 컨텍스트 메뉴에서 지정하거나 해제할 수 있습니다.",
        fr: "Les raccourcis Snippet peuvent etre attribues ou effaces depuis les reglages, le menu contextuel du Dashboard et celui du panneau rapide.",
        de: "Snippet-Tastenkurzel koennen in den Einstellungen, im Dashboard-Kontextmenu und im Kontextmenu des Schnellpanels zugewiesen oder entfernt werden.",
        it: "Le scorciatoie Snippet possono essere assegnate o cancellate dalle impostazioni, dal menu contestuale del Dashboard e dal menu contestuale del pannello rapido.",
        es: "Los atajos de Snippet pueden asignarse o borrarse desde Ajustes, el menu contextual del Dashboard y el menu contextual del panel rapido.",
      },
      {
        en: "Privacy exclusion sources now include a \"Choose App\" entry for selecting installed apps and automatically reading their Bundle ID.",
        zh: "隐私设置中的排除来源新增“选择应用”入口，可直接从已安装应用中选择并自动读取 Bundle ID。",
        ja: "プライバシー設定の除外ソースに「アプリを選択」項目を追加しました。インストール済みアプリから直接選択し、Bundle ID を自動的に読み取れます。",
        ko: "개인정보 설정의 제외 소스에 \"앱 선택\" 항목을 추가했습니다. 설치된 앱에서 직접 선택하고 Bundle ID를 자동으로 읽을 수 있습니다.",
        fr: "Les sources exclues de confidentialite incluent desormais une entree \"Choose App\" pour selectionner une app installee et lire automatiquement son Bundle ID.",
        de: "Die Datenschutzausschluesse enthalten jetzt einen Eintrag \"Choose App\", um installierte Apps auszuwaehlen und deren Bundle ID automatisch zu lesen.",
        it: "Le sorgenti escluse nelle impostazioni Privacy includono ora una voce \"Choose App\" per selezionare un'app installata e leggerne automaticamente il Bundle ID.",
        es: "Las fuentes excluidas en Privacidad ahora incluyen una entrada \"Choose App\" para seleccionar apps instaladas y leer automaticamente su Bundle ID.",
      },
      {
        en: "The exclusion source list now shows app icons and app names while keeping the Bundle ID visible for advanced confirmation.",
        zh: "排除来源列表新增应用图标和应用名称显示，保留 Bundle ID 供高级用户确认。",
        ja: "除外ソースの一覧にアプリアイコンとアプリ名を表示し、上級ユーザーが確認できるよう Bundle ID も残しました。",
        ko: "제외 소스 목록에 앱 아이콘과 앱 이름을 표시하고, 고급 사용자가 확인할 수 있도록 Bundle ID도 유지합니다.",
        fr: "La liste des sources exclues affiche maintenant les icones et noms d'apps, tout en conservant le Bundle ID pour verification avancee.",
        de: "Die Liste der ausgeschlossenen Quellen zeigt jetzt App-Symbole und App-Namen, behaelt die Bundle ID aber fuer fortgeschrittene Nutzer sichtbar.",
        it: "L'elenco delle sorgenti escluse mostra ora icone e nomi delle app, mantenendo visibile il Bundle ID per gli utenti avanzati.",
        es: "La lista de fuentes excluidas ahora muestra iconos y nombres de apps, y mantiene visible el Bundle ID para confirmacion avanzada.",
      },
      {
        en: "Added and refined Simplified Chinese, German, Spanish, French, Italian, Japanese, and Korean localization for the new v1.0.6 copy.",
        zh: "补充并精修 v1.0.6 新增文案的简中、德语、西班牙语、法语、意大利语、日语和韩语本地化。",
        ja: "v1.0.6 の新しい文言について、簡体字中国語、ドイツ語、スペイン語、フランス語、イタリア語、日本語、韓国語のローカライズを追加・調整しました。",
        ko: "v1.0.6의 새 문구에 대해 중국어 간체, 독일어, 스페인어, 프랑스어, 이탈리아어, 일본어, 한국어 현지화를 추가하고 다듬었습니다.",
        fr: "Ajout et affinage des localisations chinois simplifie, allemand, espagnol, francais, italien, japonais et coreen pour les nouveaux textes de v1.0.6.",
        de: "Die neuen Texte aus v1.0.6 wurden fuer vereinfachtes Chinesisch, Deutsch, Spanisch, Franzoesisch, Italienisch, Japanisch und Koreanisch ergaenzt und verfeinert.",
        it: "Aggiunte e rifinite le localizzazioni in cinese semplificato, tedesco, spagnolo, francese, italiano, giapponese e coreano per i nuovi testi di v1.0.6.",
        es: "Se agregaron y pulieron las localizaciones en chino simplificado, aleman, espanol, frances, italiano, japones y coreano para los nuevos textos de v1.0.6.",
      },
      {
        en: "Thanks to Alex Chen, Emily Roberts, and Sam Wilson for their UserJot feedback that shaped pinned sync and Snippet hotkeys.",
        zh: "感谢 Alex Chen、Emily Roberts、Sam Wilson 在 UserJot 上提供的反馈，推动了置顶同步和 Snippet 快捷键功能。",
        ja: "ピン留め同期と Snippet ホットキーの実現につながる UserJot フィードバックを寄せてくれた Alex Chen、Emily Roberts、Sam Wilson に感謝します。",
        ko: "고정 동기화와 Snippet 단축키 기능에 도움을 준 UserJot 피드백을 제공한 Alex Chen, Emily Roberts, Sam Wilson에게 감사드립니다.",
        fr: "Merci a Alex Chen, Emily Roberts et Sam Wilson pour leurs retours sur UserJot, qui ont contribue a la synchronisation des elements epingles et aux raccourcis Snippet.",
        de: "Danke an Alex Chen, Emily Roberts und Sam Wilson fuer ihr Feedback auf UserJot, das die Synchronisierung angehefteter Inhalte und die Snippet-Tastenkurzel vorangebracht hat.",
        it: "Grazie ad Alex Chen, Emily Roberts e Sam Wilson per il feedback su UserJot che ha contribuito alla sincronizzazione degli elementi fissati e alle scorciatoie Snippet.",
        es: "Gracias a Alex Chen, Emily Roberts y Sam Wilson por sus comentarios en UserJot, que impulsaron la sincronizacion de elementos fijados y los atajos de Snippet.",
      },
    ],
  },
  {
    version: "1.0.5",
    date: "2026-06-05",
    title: {
      en: "Image OCR upgrades, sensitive indicators, and statistics insights",
      zh: "图片 OCR 升级、敏感标识与统计洞察",
      ja: "画像 OCR の改善、機密表示、統計インサイト",
      ko: "이미지 OCR 개선, 민감 표시 및 통계 인사이트",
      fr: "Ameliorations OCR d'image, indicateurs sensibles et statistiques",
      de: "Verbesserte Bild-OCR, sensible Markierungen und Statistik-Einblicke",
      it: "Miglioramenti OCR immagini, indicatori sensibili e statistiche",
      es: "Mejoras de OCR de imagenes, indicadores sensibles y estadisticas",
    },
    notes: [
      {
        en: "The OCR action for image records moved from the `AI Actions` submenu to a standalone \"Extract Image Text\" command in the context menu.",
        zh: "图片记录的 OCR 操作从 `AI Actions` 子菜单提升为右键菜单中的独立“提取图片文本”命令。",
        ja: "画像記録の OCR 操作を `AI Actions` サブメニューからコンテキストメニュー内の独立した「画像テキストを抽出」コマンドへ移動しました。",
        ko: "이미지 기록의 OCR 작업을 `AI Actions` 하위 메뉴에서 컨텍스트 메뉴의 독립적인 \"이미지 텍스트 추출\" 명령으로 옮겼습니다.",
        fr: "L'action OCR des enregistrements image passe du sous-menu `AI Actions` a une commande autonome \"Extract Image Text\" dans le menu contextuel.",
        de: "Die OCR-Aktion fuer Bildeintraege wurde aus dem Untermenue `AI Actions` in einen eigenen Kontextmenue-Befehl \"Extract Image Text\" verschoben.",
        it: "L'azione OCR dei record immagine e stata spostata dal sottomenu `AI Actions` a un comando autonomo \"Extract Image Text\" nel menu contestuale.",
        es: "La accion OCR de los registros de imagen paso del submenu `AI Actions` a un comando independiente \"Extract Image Text\" en el menu contextual.",
      },
      {
        en: "Improved Chinese recognition for image OCR by preferring CGImage creation from original image data, upscaling low-resolution images, and explicitly enabling Chinese and other multilingual candidates.",
        zh: "改进图片 OCR 的中文识别：优先从原始图片数据创建 CGImage，低分辨率图片会放大后识别，并显式启用中文等多语言候选。",
        ja: "画像 OCR の中国語認識を改善しました。元画像データからの CGImage 作成を優先し、低解像度画像は拡大して認識し、中国語など複数言語の候補を明示的に有効化します。",
        ko: "이미지 OCR의 중국어 인식을 개선했습니다. 원본 이미지 데이터에서 CGImage 생성을 우선하고, 저해상도 이미지는 확대 후 인식하며, 중국어 등 다국어 후보를 명시적으로 활성화합니다.",
        fr: "Amelioration de la reconnaissance chinoise pour l'OCR d'image : creation CGImage depuis les donnees d'origine en priorite, agrandissement des images basse resolution et activation explicite du chinois et d'autres candidats multilingues.",
        de: "Die chinesische Erkennung der Bild-OCR wurde verbessert: CGImage wird bevorzugt aus den Originalbilddaten erstellt, niedrig aufgeloeste Bilder werden vor der Erkennung vergroessert, und Chinesisch sowie weitere mehrsprachige Kandidaten werden explizit aktiviert.",
        it: "Migliorato il riconoscimento del cinese nell'OCR immagini: creazione CGImage preferita dai dati immagine originali, ingrandimento delle immagini a bassa risoluzione e abilitazione esplicita di cinese e altri candidati multilingue.",
        es: "Se mejoro el reconocimiento de chino en OCR de imagenes: se prioriza crear CGImage desde los datos originales, se amplian las imagenes de baja resolucion y se habilitan explicitamente chino y otros candidatos multilingues.",
      },
      {
        en: "The image OCR result panel now shows \"Recognition technology: Apple Vision\" below the result, clarifying the source without polluting copied text.",
        zh: "图片 OCR 结果面板下方新增“识别技术: Apple Vision”标识，说明识别来源且不污染可复制文本。",
        ja: "画像 OCR の結果パネル下部に「認識技術: Apple Vision」表示を追加し、コピー可能なテキストを汚さず認識元を明示しました。",
        ko: "이미지 OCR 결과 패널 아래에 \"인식 기술: Apple Vision\" 표시를 추가해 복사 가능한 텍스트를 오염시키지 않고 인식 출처를 명확히 합니다.",
        fr: "Le panneau de resultat OCR d'image affiche maintenant \"Recognition technology: Apple Vision\" sous le resultat, afin de clarifier la source sans polluer le texte copiable.",
        de: "Das Ergebnisfenster der Bild-OCR zeigt unter dem Ergebnis jetzt \"Recognition technology: Apple Vision\", um die Quelle zu erklaeren, ohne den kopierbaren Text zu veraendern.",
        it: "Il pannello dei risultati OCR immagine ora mostra \"Recognition technology: Apple Vision\" sotto il risultato, chiarendo l'origine senza contaminare il testo copiabile.",
        es: "El panel de resultados de OCR de imagen ahora muestra \"Recognition technology: Apple Vision\" debajo del resultado, aclarando el origen sin contaminar el texto copiable.",
      },
      {
        en: "Sensitive records in Dashboard and the quick panel now show a `key.circle` indicator.",
        zh: "Dashboard 和快捷面板中的敏感记录新增 `key.circle` 标识。",
        ja: "Dashboard とクイックパネルの機密記録に `key.circle` インジケータを追加しました。",
        ko: "Dashboard와 빠른 패널의 민감한 기록에 `key.circle` 표시를 추가했습니다.",
        fr: "Les enregistrements sensibles du Dashboard et du panneau rapide affichent desormais l'indicateur `key.circle`.",
        de: "Sensible Eintraege in Dashboard und Schnellpanel zeigen jetzt eine `key.circle`-Markierung.",
        it: "I record sensibili in Dashboard e nel pannello rapido ora mostrano l'indicatore `key.circle`.",
        es: "Los registros sensibles en Dashboard y el panel rapido ahora muestran el indicador `key.circle`.",
      },
      {
        en: "The statistics panel now analyzes sensitive copies, ignored copies, and pause counts, with a new statistics entry point in the quick panel.",
        zh: "统计面板新增敏感复制、忽略次数、暂停次数分析，并在快捷面板新增统计入口。",
        ja: "統計パネルに機密コピー、無視回数、一時停止回数の分析を追加し、クイックパネルにも統計への入口を追加しました。",
        ko: "통계 패널에 민감한 복사, 무시 횟수, 일시 중지 횟수 분석을 추가하고 빠른 패널에 통계 진입점을 추가했습니다.",
        fr: "Le panneau de statistiques analyse maintenant les copies sensibles, les copies ignorees et les pauses, avec une nouvelle entree Statistiques dans le panneau rapide.",
        de: "Der Statistikbereich analysiert jetzt sensible Kopien, ignorierte Kopien und Pausenzaehlungen; ausserdem gibt es im Schnellpanel einen neuen Statistik-Einstieg.",
        it: "Il pannello statistiche ora analizza copie sensibili, conteggi ignorati e pause, con un nuovo accesso alle statistiche nel pannello rapido.",
        es: "El panel de estadisticas ahora analiza copias sensibles, conteos ignorados y pausas, con una nueva entrada de estadisticas en el panel rapido.",
      },
      {
        en: "The statistics panel adds copy source statistics with source icons, plus dynamic loading and rendering effects for values and charts.",
        zh: "统计面板新增带来源图标的复制来源统计，并为数值和图表增加动态加载渲染效果。",
        ja: "統計パネルにソースアイコン付きのコピー元統計を追加し、数値とグラフに動的な読み込み・描画エフェクトを追加しました。",
        ko: "통계 패널에 소스 아이콘이 있는 복사 소스 통계를 추가하고 숫자와 차트에 동적 로딩 및 렌더링 효과를 추가했습니다.",
        fr: "Le panneau de statistiques ajoute des statistiques de sources de copie avec icones de source, ainsi que des effets dynamiques de chargement et de rendu pour les valeurs et graphiques.",
        de: "Der Statistikbereich bietet jetzt Kopierquellen-Statistiken mit Quellensymbolen sowie dynamische Lade- und Rendereffekte fuer Werte und Diagramme.",
        it: "Il pannello statistiche aggiunge statistiche sulle sorgenti di copia con icone, oltre a effetti dinamici di caricamento e rendering per valori e grafici.",
        es: "El panel de estadisticas agrega estadisticas de fuentes de copia con iconos, ademas de efectos dinamicos de carga y renderizado para valores y graficos.",
      },
      {
        en: "Added AI usage statistics to the statistics panel, showing real tokens, cache hits, provider/model distribution, and model-price-based cost estimates by period.",
        zh: "统计面板新增 AI 用量统计，按周期展示真实 token、缓存命中、服务商/模型分布和基于模型价格的费用估算。",
        ja: "統計パネルに AI 使用量統計を追加し、期間ごとの実トークン、キャッシュヒット、プロバイダー/モデル分布、モデル価格に基づく費用見積もりを表示します。",
        ko: "통계 패널에 AI 사용량 통계를 추가해 기간별 실제 토큰, 캐시 적중, 제공업체/모델 분포, 모델 가격 기반 비용 추정을 표시합니다.",
        fr: "Ajout de statistiques d'utilisation IA dans le panneau de statistiques, avec tokens reels, cache hits, repartition fournisseur/modele et estimation des couts selon les prix des modeles par periode.",
        de: "AI-Nutzungsstatistiken im Statistikbereich hinzugefuegt, mit echten Tokens, Cache-Treffern, Anbieter-/Modellverteilung und periodenbezogenen Kostenschaetzungen auf Basis der Modellpreise.",
        it: "Aggiunte statistiche di utilizzo AI nel pannello statistiche, con token reali, cache hit, distribuzione provider/modello e stime dei costi basate sui prezzi dei modelli per periodo.",
        es: "Se agregaron estadisticas de uso de IA al panel de estadisticas, mostrando tokens reales, aciertos de cache, distribucion proveedor/modelo y estimaciones de costo por periodo basadas en precios de modelos.",
      },
      {
        en: "Removed the duplicate AI Usage block from AI settings. AI usage is now viewed from the statistics panel.",
        zh: "AI 设置页移除重复的 AI Usage 区块，AI 用量统一在统计面板查看。",
        ja: "AI 設定ページから重複していた AI Usage ブロックを削除しました。AI 使用量は統計パネルで一元的に確認できます。",
        ko: "AI 설정 페이지에서 중복된 AI Usage 블록을 제거했습니다. AI 사용량은 이제 통계 패널에서 통합해 확인합니다.",
        fr: "Suppression du bloc AI Usage en double dans les reglages IA. L'utilisation IA se consulte desormais dans le panneau de statistiques.",
        de: "Der doppelte AI Usage-Block wurde aus den AI-Einstellungen entfernt. Die AI-Nutzung wird jetzt zentral im Statistikbereich angezeigt.",
        it: "Rimosso il blocco AI Usage duplicato dalle impostazioni AI. L'utilizzo AI ora si consulta nel pannello statistiche.",
        es: "Se elimino el bloque duplicado AI Usage de los ajustes de IA. El uso de IA ahora se consulta desde el panel de estadisticas.",
      },
    ],
  },
  {
    version: "1.0.4",
    date: "2026-06-04",
    title: {
      en: "Sensitive capture controls, masked previews, and local image OCR",
      zh: "敏感复制控制、脱敏预览与本地图片 OCR",
      ja: "機密コピー制御、マスク表示、ローカル画像 OCR",
      ko: "민감한 복사 제어, 마스킹 미리보기 및 로컬 이미지 OCR",
      fr: "Controle des copies sensibles, apercus masques et OCR local des images",
      de: "Steuerung sensibler Kopien, maskierte Vorschauen und lokale Bild-OCR",
      it: "Controlli per copie sensibili, anteprime mascherate e OCR locale immagini",
      es: "Controles de copia sensible, vistas enmascaradas y OCR local de imagenes",
    },
    notes: [
      {
        en: "Added a temporary \"Record Sensitive Copies\" switch to the quick panel. While enabled, Clibo bypasses sensitive filtering and changes the menu bar icon to `lock.slash`; turning it off restores the normal privacy rules.",
        zh: "快捷面板新增临时“记录敏感复制”开关。开启期间会绕过敏感过滤并让菜单栏图标切换为 `lock.slash`，关闭后恢复正常隐私规则。",
        ja: "クイックパネルに一時的な「機密コピーを記録」スイッチを追加しました。有効な間は機密フィルターをバイパスし、メニューバーアイコンが `lock.slash` に切り替わります。オフにすると通常のプライバシールールに戻ります。",
        ko: "빠른 패널에 임시 \"민감한 복사 기록\" 스위치를 추가했습니다. 켜져 있는 동안 민감한 필터링을 우회하고 메뉴 막대 아이콘이 `lock.slash`로 바뀌며, 끄면 일반 개인정보 보호 규칙으로 돌아갑니다.",
        fr: "Ajout d'un interrupteur temporaire \"Record Sensitive Copies\" dans le panneau rapide. Lorsqu'il est active, Clibo contourne le filtrage sensible et remplace l'icone de barre de menus par `lock.slash`; une fois desactive, les regles de confidentialite normales sont restaurees.",
        de: "Im Schnellpanel gibt es einen temporaeren Schalter \"Record Sensitive Copies\". Solange er aktiv ist, umgeht Clibo den Filter fuer sensible Inhalte und wechselt das Menuleistensymbol zu `lock.slash`; nach dem Deaktivieren gelten wieder die normalen Datenschutzregeln.",
        it: "Aggiunto al pannello rapido un interruttore temporaneo \"Record Sensitive Copies\". Quando e attivo, Clibo aggira il filtro dei contenuti sensibili e cambia l'icona della barra dei menu in `lock.slash`; disattivandolo tornano le normali regole di privacy.",
        es: "Se agrego al panel rapido un interruptor temporal \"Record Sensitive Copies\". Mientras esta activado, Clibo omite el filtrado sensible y cambia el icono de la barra de menus a `lock.slash`; al desactivarlo se restauran las reglas normales de privacidad.",
      },
      {
        en: "Sensitive content is masked by default in panels and can be disabled in Privacy settings; copying, pasting, and database storage still use the original content.",
        zh: "敏感内容默认在面板中脱敏显示，可在隐私设置中关闭；复制、粘贴和数据库存储仍使用原始内容。",
        ja: "機密内容はデフォルトでパネル内ではマスク表示され、プライバシー設定で無効化できます。コピー、貼り付け、データベース保存には引き続き元の内容が使われます。",
        ko: "민감한 콘텐츠는 기본적으로 패널에서 마스킹되어 표시되며 개인정보 설정에서 끌 수 있습니다. 복사, 붙여넣기 및 데이터베이스 저장에는 여전히 원본 콘텐츠가 사용됩니다.",
        fr: "Le contenu sensible est masque par defaut dans les panneaux et peut etre desactive dans les reglages de confidentialite; la copie, le collage et le stockage en base de donnees utilisent toujours le contenu d'origine.",
        de: "Sensible Inhalte werden in Panels standardmaessig maskiert angezeigt und koennen in den Datenschutzeinstellungen deaktiviert werden; Kopieren, Einfuegen und Datenbankspeicherung verwenden weiterhin den Originalinhalt.",
        it: "I contenuti sensibili sono mascherati per impostazione predefinita nei pannelli e possono essere disattivati nelle impostazioni Privacy; copia, incolla e archiviazione nel database usano ancora il contenuto originale.",
        es: "El contenido sensible se muestra enmascarado por defecto en los paneles y puede desactivarse en los ajustes de privacidad; copiar, pegar y almacenar en la base de datos siguen usando el contenido original.",
      },
      {
        en: "Added local OCR text extraction to the image record context menu, using Apple Vision to recognize text in images without configuring an AI provider.",
        zh: "图片记录右键菜单新增本地 OCR 文本提取功能，使用 Apple Vision 识别图片文字，无需配置 AI provider。",
        ja: "画像記録のコンテキストメニューにローカル OCR テキスト抽出を追加しました。Apple Vision で画像内の文字を認識するため、AI provider の設定は不要です。",
        ko: "이미지 기록 컨텍스트 메뉴에 로컬 OCR 텍스트 추출 기능을 추가했습니다. Apple Vision으로 이미지의 텍스트를 인식하므로 AI provider 설정이 필요 없습니다.",
        fr: "Ajout de l'extraction de texte OCR locale au menu contextuel des images, avec Apple Vision pour reconnaitre le texte des images sans configurer d'AI provider.",
        de: "Das Kontextmenu fuer Bildeintraege bietet jetzt lokale OCR-Textextraktion mit Apple Vision, um Text in Bildern ohne konfigurierten AI provider zu erkennen.",
        it: "Aggiunta l'estrazione testo OCR locale al menu contestuale dei record immagine, usando Apple Vision per riconoscere il testo nelle immagini senza configurare un AI provider.",
        es: "Se agrego extraccion local de texto OCR al menu contextual de los registros de imagen, usando Apple Vision para reconocer texto en imagenes sin configurar un AI provider.",
      },
    ],
  },
  {
    version: "1.0.3",
    date: "2026-06-01",
    title: {
      en: "Snippets, statistics, local actions, and stronger automations",
      zh: "Snippets、统计、本地操作与自动化增强",
      ja: "Snippets、統計、ローカル操作、自動化の強化",
      ko: "Snippets, 통계, 로컬 작업 및 자동화 강화",
      fr: "Snippets, statistiques, actions locales et automatisations renforcees",
      de: "Snippets, Statistiken, lokale Aktionen und staerkere Automatisierungen",
      it: "Snippets, statistiche, azioni locali e automazioni piu potenti",
      es: "Snippets, estadisticas, acciones locales y automatizaciones mas potentes",
    },
    notes: [
      {
        en: "Added a Snippets template area for creating, editing, searching, copying, pasting, and deleting reusable content.",
        zh: "新增 Snippets 模板区，支持创建、编辑、搜索、复制、粘贴和删除常用内容。",
        ja: "よく使う内容を作成、編集、検索、コピー、貼り付け、削除できる Snippets テンプレートエリアを追加しました。",
        ko: "자주 쓰는 내용을 만들기, 편집, 검색, 복사, 붙여넣기, 삭제할 수 있는 Snippets 템플릿 영역을 추가했습니다.",
        fr: "Ajout d'une zone de modeles Snippets pour creer, modifier, rechercher, copier, coller et supprimer du contenu reutilisable.",
        de: "Snippets-Vorlagenbereich zum Erstellen, Bearbeiten, Suchen, Kopieren, Einfuegen und Loeschen haeufig genutzter Inhalte hinzugefuegt.",
        it: "Aggiunta un'area template Snippets per creare, modificare, cercare, copiare, incollare ed eliminare contenuti riutilizzabili.",
        es: "Se agrego un area de plantillas Snippets para crear, editar, buscar, copiar, pegar y eliminar contenido reutilizable.",
      },
      {
        en: "Added a statistics panel in Settings for viewing copied data volume, category distribution, and an activity grid by period.",
        zh: "设置中新增统计面板，支持按周期查看复制数据量、分类分布和活跃度网格。",
        ja: "設定に統計パネルを追加し、期間ごとのコピー量、カテゴリ分布、アクティビティグリッドを確認できるようにしました。",
        ko: "설정에 통계 패널을 추가해 기간별 복사 데이터량, 카테고리 분포, 활동도 그리드를 볼 수 있게 했습니다.",
        fr: "Ajout d'un panneau de statistiques dans les reglages pour consulter le volume copie, la repartition par categorie et la grille d'activite par periode.",
        de: "Statistikbereich in den Einstellungen hinzugefuegt, um kopiertes Datenvolumen, Kategorienverteilung und Aktivitaetsraster nach Zeitraum anzuzeigen.",
        it: "Aggiunto un pannello statistiche nelle impostazioni per visualizzare volume dei dati copiati, distribuzione per categoria e griglia di attivita per periodo.",
        es: "Se agrego un panel de estadisticas en Ajustes para ver volumen copiado, distribucion por categorias y una cuadricula de actividad por periodo.",
      },
      {
        en: "Added local actions for JSON / XML formatting, Base64 encoding and decoding, and more, without requiring an AI provider.",
        zh: "新增 JSON / XML 格式化、Base64 编解码等本地 AI 操作，无需配置 AI provider。",
        ja: "AI provider の設定なしで使える、JSON / XML フォーマット、Base64 エンコード/デコードなどのローカル AI 操作を追加しました。",
        ko: "AI provider 설정 없이 사용할 수 있는 JSON / XML 포맷팅, Base64 인코딩/디코딩 등 로컬 AI 작업을 추가했습니다.",
        fr: "Ajout d'actions locales comme le formatage JSON / XML et l'encodage/decodage Base64, sans configuration d'un AI provider.",
        de: "Lokale Aktionen wie JSON-/XML-Formatierung sowie Base64-Kodierung und -Dekodierung hinzugefuegt, ohne AI provider konfigurieren zu muessen.",
        it: "Aggiunte azioni locali come formattazione JSON / XML e codifica/decodifica Base64, senza configurare un AI provider.",
        es: "Se agregaron acciones locales como formateo JSON / XML y codificacion/decodificacion Base64, sin configurar un AI provider.",
      },
      {
        en: "Added an Explain Code AI action and support for configuring the translation target language.",
        zh: "新增 Explain Code AI 操作，并支持配置翻译目标语言。",
        ja: "Explain Code AI 操作を追加し、翻訳先言語を設定できるようにしました。",
        ko: "Explain Code AI 작업을 추가하고 번역 대상 언어 설정을 지원합니다.",
        fr: "Ajout de l'action AI Explain Code et de la configuration de la langue cible de traduction.",
        de: "Explain Code AI-Aktion hinzugefuegt und Konfiguration der Zieluebersetzungssprache unterstuetzt.",
        it: "Aggiunta l'azione AI Explain Code e il supporto per configurare la lingua di destinazione della traduzione.",
        es: "Se agrego la accion AI Explain Code y soporte para configurar el idioma de destino de traduccion.",
      },
      {
        en: "Enhanced automation rules with multi-condition AND, chained actions, and triggers for content length, regex, and JSON detection.",
        zh: "增强自动化规则，支持多条件 AND、多动作链，以及内容长度、正则、JSON 检测触发器。",
        ja: "自動化ルールを強化し、複数条件 AND、アクションチェーン、内容長、正規表現、JSON 検出トリガーをサポートしました。",
        ko: "자동화 규칙을 강화해 다중 조건 AND, 여러 작업 체인, 콘텐츠 길이, 정규식, JSON 감지 트리거를 지원합니다.",
        fr: "Renforcement des regles d'automatisation avec AND multi-conditions, chaines d'actions et declencheurs de longueur, regex et detection JSON.",
        de: "Automatisierungsregeln mit Mehrfachbedingungen per AND, Aktionsketten sowie Triggern fuer Inhaltslaenge, Regex und JSON-Erkennung erweitert.",
        it: "Regole di automazione potenziate con AND multi-condizione, catene di azioni e trigger per lunghezza contenuto, regex e rilevamento JSON.",
        es: "Reglas de automatizacion mejoradas con AND de multiples condiciones, cadenas de acciones y disparadores de longitud, regex y deteccion JSON.",
      },
      {
        en: "Added automation actions for saving to file, running macOS Shortcuts, and copying as plain text.",
        zh: "自动化动作新增保存到文件、运行 macOS Shortcuts、复制为纯文本。",
        ja: "ファイルへ保存、macOS Shortcuts の実行、プレーンテキストとしてコピーする自動化アクションを追加しました。",
        ko: "파일로 저장, macOS Shortcuts 실행, 일반 텍스트로 복사하는 자동화 작업을 추가했습니다.",
        fr: "Ajout d'actions d'automatisation pour enregistrer dans un fichier, executer macOS Shortcuts et copier en texte brut.",
        de: "Automatisierungsaktionen zum Speichern in Dateien, Ausfuehren von macOS Shortcuts und Kopieren als Nur-Text hinzugefuegt.",
        it: "Aggiunte azioni di automazione per salvare su file, eseguire macOS Shortcuts e copiare come testo semplice.",
        es: "Se agregaron acciones de automatizacion para guardar en archivo, ejecutar macOS Shortcuts y copiar como texto plano.",
      },
      {
        en: "Dashboard and quick panel content type icons now use type-based colors.",
        zh: "Dashboard 和快捷面板的内容类型图标改为按类型着色。",
        ja: "Dashboard とクイックパネルのコンテンツタイプアイコンが、タイプ別の色で表示されるようになりました。",
        ko: "Dashboard와 빠른 패널의 콘텐츠 유형 아이콘이 유형별 색상으로 표시됩니다.",
        fr: "Les icones de type de contenu du Dashboard et du panneau rapide utilisent desormais des couleurs par type.",
        de: "Inhaltstyp-Symbole in Dashboard und Schnellpanel verwenden jetzt typspezifische Farben.",
        it: "Le icone dei tipi di contenuto in Dashboard e nel pannello rapido ora usano colori basati sul tipo.",
        es: "Los iconos de tipo de contenido en Dashboard y el panel rapido ahora usan colores segun el tipo.",
      },
    ],
  },
  {
    version: "1.0.2",
    date: "2026-05-31",
    title: {
      en: "Documentation, tests, trial updates, and internal refactors",
      zh: "文档、测试、试用期更新与内部重构",
      ja: "ドキュメント、テスト、トライアル更新、内部リファクタリング",
      ko: "문서, 테스트, 체험 기간 업데이트 및 내부 리팩터링",
      fr: "Documentation, tests, essai et refactorisations internes",
      de: "Dokumentation, Tests, Testzeitraum und interne Refactorings",
      it: "Documentazione, test, prova e refactoring interni",
      es: "Documentacion, pruebas, periodo de prueba y refactorizaciones internas",
    },
    notes: [
      {
        en: "Added a README with product overview, installation, system requirements, privacy notes, trial, and license information.",
        zh: "新增 README，补充产品介绍、安装方式、系统要求、隐私说明、试用和许可证信息。",
        ja: "README を追加し、製品紹介、インストール方法、システム要件、プライバシー説明、トライアル、ライセンス情報を補足しました。",
        ko: "제품 소개, 설치 방법, 시스템 요구 사항, 개인정보 안내, 체험판 및 라이선스 정보를 담은 README를 추가했습니다.",
        fr: "Ajout d'un README avec la presentation du produit, l'installation, les prerequis systeme, la confidentialite, l'essai et les informations de licence.",
        de: "README mit Produktuberblick, Installation, Systemanforderungen, Datenschutzhinweisen, Testversion und Lizenzinformationen hinzugefugt.",
        it: "Aggiunto un README con panoramica del prodotto, installazione, requisiti di sistema, privacy, prova e informazioni sulla licenza.",
        es: "Se agrego un README con descripcion del producto, instalacion, requisitos del sistema, privacidad, prueba e informacion de licencia.",
      },
      {
        en: "Added a SwiftPM test target covering color parsing, automation rule matching, clipboard database migrations, and basic search flows.",
        zh: "新增 SwiftPM 测试 target，覆盖颜色解析、自动化规则匹配、剪贴板数据库迁移与基础搜索流程。",
        ja: "色解析、自動化ルール照合、クリップボードデータベース移行、基本検索フローを対象にした SwiftPM テスト target を追加しました。",
        ko: "색상 파싱, 자동화 규칙 매칭, 클립보드 데이터베이스 마이그레이션, 기본 검색 흐름을 다루는 SwiftPM 테스트 target을 추가했습니다.",
        fr: "Ajout d'une cible de test SwiftPM couvrant l'analyse des couleurs, les regles d'automatisation, les migrations de base de donnees du presse-papiers et les flux de recherche de base.",
        de: "SwiftPM-Testtarget fur Farbparsing, Automatisierungsregel-Abgleich, Migrationen der Zwischenablage-Datenbank und grundlegende Suchablaufe hinzugefugt.",
        it: "Aggiunto un target di test SwiftPM per parsing dei colori, corrispondenza delle regole di automazione, migrazioni del database degli appunti e flussi di ricerca di base.",
        es: "Se agrego un target de pruebas SwiftPM para analisis de colores, coincidencia de reglas de automatizacion, migraciones de la base de datos del portapapeles y flujos basicos de busqueda.",
      },
      {
        en: "Added a SQLite `user_version` migration mechanism as the foundation for future database schema iterations.",
        zh: "新增 SQLite `user_version` 迁移机制，为后续数据库 schema 迭代提供基础。",
        ja: "今後のデータベース schema 反復の基盤として、SQLite `user_version` 移行メカニズムを追加しました。",
        ko: "향후 데이터베이스 schema 변경을 위한 기반으로 SQLite `user_version` 마이그레이션 메커니즘을 추가했습니다.",
        fr: "Ajout d'un mecanisme de migration SQLite `user_version` comme base pour les futures evolutions du schema de base de donnees.",
        de: "SQLite-`user_version`-Migrationsmechanismus als Grundlage fur kunftige Datenbankschema-Iterationen hinzugefugt.",
        it: "Aggiunto un meccanismo di migrazione SQLite `user_version` come base per future iterazioni dello schema del database.",
        es: "Se agrego un mecanismo de migracion SQLite `user_version` como base para futuras iteraciones del schema de la base de datos.",
      },
      {
        en: "Sparkle appcast generation now supports injecting localized release notes and uploading them.",
        zh: "Sparkle appcast 生成流程新增本地化 release notes 注入与上传支持。",
        ja: "Sparkle appcast 生成フローで、ローカライズされた release notes の注入とアップロードをサポートしました。",
        ko: "Sparkle appcast 생성 흐름에 현지화된 release notes 주입 및 업로드 지원을 추가했습니다.",
        fr: "La generation d'appcast Sparkle prend desormais en charge l'injection et l'envoi des release notes localisees.",
        de: "Die Sparkle-Appcast-Erzeugung unterstutzt jetzt das Einfugen und Hochladen lokalisierter Release Notes.",
        it: "La generazione degli appcast Sparkle ora supporta l'inserimento e il caricamento delle release notes localizzate.",
        es: "La generacion de appcast de Sparkle ahora admite insertar y subir release notes localizadas.",
      },
      {
        en: "Standardized the free trial period to 7 days and synced onboarding and license expiration copy.",
        zh: "免费试用期统一为 7 天，并同步 onboarding 与许可证过期文案。",
        ja: "無料トライアル期間を 7 日間に統一し、onboarding とライセンス期限切れ文言を同期しました。",
        ko: "무료 체험 기간을 7일로 통일하고 onboarding 및 라이선스 만료 문구를 동기화했습니다.",
        fr: "La periode d'essai gratuite est unifiee a 7 jours, avec synchronisation des textes d'onboarding et d'expiration de licence.",
        de: "Der kostenlose Testzeitraum wurde auf 7 Tage vereinheitlicht; Onboarding- und Lizenzablauftexte wurden synchronisiert.",
        it: "Il periodo di prova gratuito e stato uniformato a 7 giorni, con testi di onboarding e scadenza licenza sincronizzati.",
        es: "El periodo de prueba gratuito se unifico en 7 dias y se sincronizaron los textos de onboarding y vencimiento de licencia.",
      },
      {
        en: "Added an onboarding screen for core value and local privacy messaging.",
        zh: "Onboarding 新增一屏核心价值与本地隐私提示。",
        ja: "onboarding に、主要価値とローカルプライバシーを伝える画面を追加しました。",
        ko: "onboarding에 핵심 가치와 로컬 개인정보 보호 안내 화면을 추가했습니다.",
        fr: "Ajout d'un ecran d'onboarding pour la valeur principale et le message de confidentialite locale.",
        de: "Onboarding um einen Bildschirm fur Kernnutzen und lokale Datenschutzhinweise erweitert.",
        it: "Aggiunta una schermata di onboarding per valore principale e messaggio sulla privacy locale.",
        es: "Se agrego una pantalla de onboarding para el valor principal y el mensaje de privacidad local.",
      },
      {
        en: "Moved Keychain management into the shared App layer instead of keeping it under the AI module.",
        zh: "将 Keychain 管理移动到 App 共享层，避免继续挂在 AI 模块下。",
        ja: "Keychain 管理を AI モジュール配下から App 共有レイヤーへ移動しました。",
        ko: "Keychain 관리를 AI 모듈 아래가 아닌 App 공유 계층으로 이동했습니다.",
        fr: "Deplacement de la gestion Keychain vers la couche partagee App, au lieu du module AI.",
        de: "Keychain-Verwaltung aus dem AI-Modul in die gemeinsame App-Schicht verschoben.",
        it: "Spostata la gestione Keychain nel livello condiviso App, invece che nel modulo AI.",
        es: "La gestion de Keychain se movio a la capa compartida App en lugar de permanecer bajo el modulo AI.",
      },
      {
        en: "Organized the Search module into Core, Dashboard, QuickPanel, and Preview subdirectories.",
        zh: "将 Search 模块按 Core、Dashboard、QuickPanel、Preview 子目录整理。",
        ja: "Search モジュールを Core、Dashboard、QuickPanel、Preview のサブディレクトリに整理しました。",
        ko: "Search 모듈을 Core, Dashboard, QuickPanel, Preview 하위 디렉터리로 정리했습니다.",
        fr: "Organisation du module Search en sous-dossiers Core, Dashboard, QuickPanel et Preview.",
        de: "Search-Modul in die Unterverzeichnisse Core, Dashboard, QuickPanel und Preview gegliedert.",
        it: "Organizzato il modulo Search nelle sottocartelle Core, Dashboard, QuickPanel e Preview.",
        es: "Se organizo el modulo Search en los subdirectorios Core, Dashboard, QuickPanel y Preview.",
      },
      {
        en: "Added a conservative SwiftLint configuration.",
        zh: "新增保守 SwiftLint 配置。",
        ja: "保守的な SwiftLint 設定を追加しました。",
        ko: "보수적인 SwiftLint 구성을 추가했습니다.",
        fr: "Ajout d'une configuration SwiftLint conservatrice.",
        de: "Konservative SwiftLint-Konfiguration hinzugefugt.",
        it: "Aggiunta una configurazione SwiftLint conservativa.",
        es: "Se agrego una configuracion conservadora de SwiftLint.",
      },
    ],
  },
  {
    version: "1.0.1",
    date: "2026-05-31",
    title: {
      en: "Quick panel improvements, path handling, and localization updates",
      zh: "快捷面板改进、路径处理与本地化更新",
      ja: "クイックパネルの改善、パス処理、ローカライズ更新",
      ko: "빠른 패널 개선, 경로 처리 및 현지화 업데이트",
      fr: "Ameliorations du panneau rapide, gestion des chemins et mises a jour de localisation",
      de: "Verbesserungen am Schnellpanel, Pfadverarbeitung und Lokalisierungsupdates",
      it: "Miglioramenti al pannello rapido, gestione dei percorsi e aggiornamenti di localizzazione",
      es: "Mejoras del panel rapido, gestion de rutas y actualizaciones de localizacion",
    },
    notes: [
      {
        en: "Color items in the quick panel now use smaller square swatches.",
        zh: "快捷面板颜色类型的列表色块改为更小的方块显示。",
        ja: "クイックパネルのカラー項目は、より小さい正方形のスウォッチで表示されるようになりました。",
        ko: "빠른 패널의 색상 항목이 더 작은 정사각형 색상 견본으로 표시됩니다.",
        fr: "Les elements de couleur du panneau rapide utilisent desormais de plus petits echantillons carres.",
        de: "Farbeintrage im Schnellpanel verwenden jetzt kleinere quadratische Farbfelder.",
        it: "Gli elementi colore nel pannello rapido ora usano campioni quadrati piu piccoli.",
        es: "Los elementos de color del panel rapido ahora usan muestras cuadradas mas pequenas.",
      },
      {
        en: "Quick panel lists now support the same context menu capabilities as Dashboard lists.",
        zh: "快捷面板列表新增与 Dashboard 列表一致的右键菜单能力。",
        ja: "クイックパネルのリストで、Dashboard リストと同じコンテキストメニュー機能を利用できるようになりました。",
        ko: "빠른 패널 목록에 Dashboard 목록과 동일한 컨텍스트 메뉴 기능이 추가되었습니다.",
        fr: "Les listes du panneau rapide prennent desormais en charge les memes menus contextuels que les listes du Dashboard.",
        de: "Listen im Schnellpanel unterstutzen jetzt dieselben Kontextmenufunktionen wie Dashboard-Listen.",
        it: "Gli elenchi del pannello rapido ora supportano le stesse funzioni del menu contestuale degli elenchi Dashboard.",
        es: "Las listas del panel rapido ahora admiten las mismas funciones de menu contextual que las listas del Dashboard.",
      },
      {
        en: "Added file copy detection fixes to avoid mistaking copied files for images.",
        zh: "新增文件复制识别修正，避免复制文件时被误识别为图片。",
        ja: "ファイルコピー検出を修正し、コピーしたファイルが画像として誤認識されないようにしました。",
        ko: "파일 복사 감지 수정으로 복사한 파일이 이미지로 잘못 인식되지 않도록 했습니다.",
        fr: "Correction de la detection de copie de fichiers afin d'eviter que les fichiers copies soient identifies a tort comme des images.",
        de: "Korrekturen bei der Erkennung kopierter Dateien verhindern, dass kopierte Dateien falsch als Bilder erkannt werden.",
        it: "Corretta l'identificazione della copia dei file per evitare che i file copiati vengano riconosciuti erroneamente come immagini.",
        es: "Se corrigio la deteccion de copia de archivos para evitar que los archivos copiados se identifiquen por error como imagenes.",
      },
      {
        en: "Added system path recognition, a dedicated icon for path items, and support for opening the location from the context menu.",
        zh: "新增系统路径识别，路径类型使用独立图标，并支持在右键菜单中打开位置。",
        ja: "システムパス認識を追加し、パス項目に専用アイコンを使用し、コンテキストメニューから場所を開けるようにしました。",
        ko: "시스템 경로 인식, 경로 유형 전용 아이콘, 컨텍스트 메뉴에서 위치 열기를 추가했습니다.",
        fr: "Ajout de la reconnaissance des chemins systeme, d'une icone dediee pour les chemins et de l'ouverture de l'emplacement depuis le menu contextuel.",
        de: "Systempfaderkennung, ein eigenes Symbol fur Pfade und das Offnen des Speicherorts uber das Kontextmenu wurden hinzugefugt.",
        it: "Aggiunti il riconoscimento dei percorsi di sistema, un'icona dedicata per i percorsi e l'apertura della posizione dal menu contestuale.",
        es: "Se agrego reconocimiento de rutas del sistema, un icono dedicado para las rutas y la opcion de abrir la ubicacion desde el menu contextual.",
      },
      {
        en: "Added automatic cleanup settings for expired history, with options for 3 days, one week, 15 days, one month, 3 months, and one year.",
        zh: "新增历史记录过期自动清理设置，支持 3 天、一周、15 天、一个月、3 个月和一年。",
        ja: "期限切れ履歴の自動クリーンアップ設定を追加し、3 日、1 週間、15 日、1 か月、3 か月、1 年を選択できるようにしました。",
        ko: "만료된 기록 자동 정리 설정을 추가했으며 3일, 1주, 15일, 1개월, 3개월, 1년 옵션을 지원합니다.",
        fr: "Ajout de parametres de nettoyage automatique de l'historique expire : 3 jours, une semaine, 15 jours, un mois, 3 mois et un an.",
        de: "Automatische Bereinigung abgelaufener Verlaufseintrage hinzugefugt, mit Optionen fur 3 Tage, eine Woche, 15 Tage, einen Monat, 3 Monate und ein Jahr.",
        it: "Aggiunte impostazioni di pulizia automatica della cronologia scaduta, con opzioni per 3 giorni, una settimana, 15 giorni, un mese, 3 mesi e un anno.",
        es: "Se agregaron ajustes de limpieza automatica del historial vencido, con opciones de 3 dias, una semana, 15 dias, un mes, 3 meses y un ano.",
      },
      {
        en: "Changed the menu bar icon to `sparkle.text.clipboard.fill` while keeping automatic light and dark mode adaptation.",
        zh: "菜单栏图标切换为 `sparkle.text.clipboard.fill`，并保持深浅色模式自适应。",
        ja: "メニューバーアイコンを `sparkle.text.clipboard.fill` に変更し、ライト/ダークモードへの自動対応を維持しました。",
        ko: "메뉴 막대 아이콘을 `sparkle.text.clipboard.fill`로 변경하고 라이트/다크 모드 자동 적응을 유지했습니다.",
        fr: "L'icone de la barre de menus devient `sparkle.text.clipboard.fill` tout en conservant l'adaptation automatique aux modes clair et sombre.",
        de: "Das Menuleistensymbol wurde auf `sparkle.text.clipboard.fill` umgestellt und passt sich weiterhin automatisch an Hell- und Dunkelmodus an.",
        it: "L'icona della barra dei menu e stata cambiata in `sparkle.text.clipboard.fill`, mantenendo l'adattamento automatico alle modalita chiara e scura.",
        es: "El icono de la barra de menus cambio a `sparkle.text.clipboard.fill` y mantiene la adaptacion automatica a los modos claro y oscuro.",
      },
      {
        en: "Segmented controls now include Spring animation feedback.",
        zh: "分段控制器增加 Spring 动画反馈。",
        ja: "セグメントコントロールに Spring アニメーションのフィードバックを追加しました。",
        ko: "세그먼트 컨트롤에 Spring 애니메이션 피드백을 추가했습니다.",
        fr: "Les controles segmentes incluent desormais un retour d'animation Spring.",
        de: "Segmentierte Steuerelemente bieten jetzt Spring-Animationsfeedback.",
        it: "I controlli segmentati ora includono un feedback con animazione Spring.",
        es: "Los controles segmentados ahora incluyen respuesta con animacion Spring.",
      },
      {
        en: "Expanded Japanese, Korean, French, German, Italian, and Spanish language packs, including key interface and system permission copy.",
        zh: "扩展日语、韩语、法语、德语、意大利语和西班牙语语言包，并补充主要界面与系统权限文案。",
        ja: "日本語、韓国語、フランス語、ドイツ語、イタリア語、スペイン語の言語パックを拡充し、主要画面とシステム権限の文言を追加しました。",
        ko: "일본어, 한국어, 프랑스어, 독일어, 이탈리아어, 스페인어 언어 팩을 확장하고 주요 화면과 시스템 권한 문구를 보완했습니다.",
        fr: "Extension des packs japonais, coreen, francais, allemand, italien et espagnol, avec les principaux textes d'interface et d'autorisations systeme.",
        de: "Japanische, koreanische, franzosische, deutsche, italienische und spanische Sprachpakete wurden erweitert, einschliesslich zentraler Oberflachen- und Systemberechtigungstexte.",
        it: "Estesi i pacchetti lingua giapponese, coreano, francese, tedesco, italiano e spagnolo, con i principali testi dell'interfaccia e dei permessi di sistema.",
        es: "Se ampliaron los paquetes de japones, coreano, frances, aleman, italiano y espanol, incluyendo textos clave de la interfaz y permisos del sistema.",
      },
    ],
  },
  {
    version: "1.0.0",
    date: "2026-05-28",
    title: {
      en: "Initial public release",
      zh: "首个公开版本",
      ja: "初回公開リリース",
      ko: "첫 공개 릴리스",
      fr: "Premiere version publique",
      de: "Erste offentliche Version",
      it: "Prima versione pubblica",
      es: "Primera version publica",
    },
    notes: [
      {
        en: "Clipboard history with local SQLite storage.",
        zh: "基于本地 SQLite 存储的剪贴板历史。",
        ja: "ローカル SQLite ストレージによるクリップボード履歴。",
        ko: "로컬 SQLite 저장소 기반 클립보드 기록.",
        fr: "Historique du presse-papiers avec stockage SQLite local.",
        de: "Zwischenablageverlauf mit lokaler SQLite-Speicherung.",
        it: "Cronologia degli appunti con archiviazione SQLite locale.",
        es: "Historial del portapapeles con almacenamiento SQLite local.",
      },
      {
        en: "Rich previews for text, images, code, links, colors, and files.",
        zh: "支持文本、图片、代码、链接、颜色和文件的丰富预览。",
        ja: "テキスト、画像、コード、リンク、色、ファイルのリッチプレビュー。",
        ko: "텍스트, 이미지, 코드, 링크, 색상, 파일의 풍부한 미리보기.",
        fr: "Apercus enrichis pour le texte, les images, le code, les liens, les couleurs et les fichiers.",
        de: "Umfangreiche Vorschauen fur Text, Bilder, Code, Links, Farben und Dateien.",
        it: "Anteprime avanzate per testo, immagini, codice, link, colori e file.",
        es: "Vistas previas enriquecidas para texto, imagenes, codigo, enlaces, colores y archivos.",
      },
      {
        en: "Pinned snippets, quick panel, and search.",
        zh: "支持 Pin 片段、快捷面板和搜索。",
        ja: "ピン留めスニペット、クイックパネル、検索。",
        ko: "고정 스니펫, 빠른 패널, 검색.",
        fr: "Extraits epingles, panneau rapide et recherche.",
        de: "Angeheftete Snippets, Schnellpanel und Suche.",
        it: "Snippet fissati, pannello rapido e ricerca.",
        es: "Fragmentos fijados, panel rapido y busqueda.",
      },
      {
        en: "Optional BYOK AI actions for translate, rewrite, and summarize.",
        zh: "可选的 BYOK AI 操作，支持翻译、改写和总结。",
        ja: "翻訳、書き換え、要約に対応する任意の BYOK AI アクション。",
        ko: "번역, 재작성, 요약을 위한 선택형 BYOK AI 작업.",
        fr: "Actions IA BYOK optionnelles pour traduire, reformuler et resumer.",
        de: "Optionale BYOK-KI-Aktionen zum Ubersetzen, Umschreiben und Zusammenfassen.",
        it: "Azioni AI BYOK opzionali per tradurre, riscrivere e riassumere.",
        es: "Acciones de IA BYOK opcionales para traducir, reescribir y resumir.",
      },
      {
        en: "Dodo Payments license activation, validation, and deactivation.",
        zh: "支持 Dodo Payments 授权激活、验证和停用。",
        ja: "Dodo Payments ライセンスの有効化、検証、無効化。",
        ko: "Dodo Payments 라이선스 활성화, 검증, 비활성화.",
        fr: "Activation, validation et desactivation des licences Dodo Payments.",
        de: "Aktivierung, Validierung und Deaktivierung von Dodo Payments-Lizenzen.",
        it: "Attivazione, convalida e disattivazione delle licenze Dodo Payments.",
        es: "Activacion, validacion y desactivacion de licencias de Dodo Payments.",
      },
    ],
  },
];

export default function Releases() {
  useNavScroll();

  return (
    <>
      <Header />

      <main className="privacy-main">
        <h1>
          <I18nText
            t={{
              en: "Release Notes",
              zh: "更新日志",
              ja: "リリースノート",
              ko: "릴리스 노트",
              fr: "Notes de version",
              de: "Versionshinweise",
              it: "Note di rilascio",
              es: "Notas de version",
            }}
          />
        </h1>
        <p className="updated">
          <I18nText
            t={{
              en: "Latest Clibo releases and product changes.",
              zh: "Clibo 最新版本和产品变更。",
              ja: "Clibo の最新リリースと製品変更。",
              ko: "최신 Clibo 릴리스와 제품 변경 사항.",
              fr: "Dernieres versions de Clibo et changements du produit.",
              de: "Neueste Clibo-Versionen und Produktanderungen.",
              it: "Ultime versioni di Clibo e modifiche al prodotto.",
              es: "Ultimas versiones de Clibo y cambios del producto.",
            }}
          />
        </p>

        {RELEASES.map((release) => (
          <section className="release-entry" key={release.version}>
            <h2>
              Clibo {release.version}
            </h2>
            <p className="updated">{release.date}</p>
            <I18nText as="p" t={release.title} />
            <ul>
              {release.notes.map((note, index) => (
                <li key={index}>
                  <I18nText t={note} />
                </li>
              ))}
            </ul>
          </section>
        ))}
      </main>

      <Footer />
    </>
  );
}
